export const cartActions = {
    'ADD_ITEM': 'ADD_ITEM',
    'EDIT_ITEM': 'EDIT_ITEM',
    'INCREMENT_ITEM': 'INCREMENT_ITEM',
    'DECREMENT_ITEM': 'DECREMENT_ITEM',
    'REMOVE_ITEM': 'REMOVE_ITEM',
    'CLEAR_CART': 'CLEAR_CART',
}
